name: Trigger Google Apps Script

on:
  schedule:
    - cron: "55 23 * * *"   # 06:51 WIB (contoh tambahan)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Call Apps Script WebApp
        run: |
          curl -X GET "https://script.google.com/macros/s/AKfycbxja77vXi92rzOSBtAr3VquDaTkNldHbLcf22FQtdbegNzZZ0f0Jn6Nqs4pEOeP5d7rDQ/exec"
